cert-manager:
  enabled: true
  crds:
    enabled: true

cert-manager-webhook-ovh:
  enabled: true
  # configVersion is required when cert-manager-webhook-ovh is enabled
  # Must be set to "0.0.2" for this chart version
  configVersion: "0.0.2"
