{{/* Render persistent volumes */}}
{{- include "common.manifests.persistentVolume" . | nindent 0 -}}

{{/* Render persistent volume claims */}}
{{- include "common.manifests.persistentVolumeClaim" . | nindent 0 -}}
