blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/trowaflo/helm-charts/discussions
    about: Ask questions or discuss ideas in GitHub Discussions
  - name: Security Vulnerability
    url: https://github.com/trowaflo/helm-charts/security/advisories/new
    about: Report security vulnerabilities privately
