---
image:
  repository: guacamole/guacamole
  tag: 1.5.5

guacd:
  image:
    repository: guacamole/guacd
    tag: 1.5.5
  resources:
    requests:
      cpu: 1m

app:
  resources:
    requests:
      cpu: 3m

db:
  resources:
    requests:
      cpu: 10m

helper:
  resources:
    requests:
      cpu: 5m
