apiVersion: v2
name: grafana
version: 0.1.7
description: Chart to agregate existent helm chart with custom object
dependencies:
  - name: grafana
    version: 9.4.5
    repository: https://grafana.github.io/helm-charts
maintainers:
  - name: trowaflo
    email: trowa.flo@gmail.com
