apiVersion: v2
name: kgateway-platform
version: 0.1.0
type: application
description: |-
  Helm chart for configuring the kgateway platform using the Kubernetes Gateway API, including public/private gateways, HTTP(S) routing, and TLS certificate integration.
keywords:
  - kubernetes
  - gateway
  - kgateway
  - networking
  - tls

maintainers:
  - name: trowaflo
    email: trowa.flo@gmail.com
sources:
  - https://github.com/kgateway-dev/kgateway
  - https://docs.kgateway.dev/
  - https://github.com/trowaflo/helm-charts
dependencies:
  - name: common
    version: 2.0.0
    repository: https://trowaflo.github.io/helm-charts
  - name: kgateway-crds
    version: v2.1.1
    repository: oci://cr.kgateway.dev/kgateway-dev/charts
    alias: kgateway-crds
    condition: kgateway-crds.enabled
  - name: kgateway
    version: v2.1.1
    repository: oci://cr.kgateway.dev/kgateway-dev/charts
    alias: kgateway
    condition: kgateway.enabled
